spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProductsDB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: D0UGL@$mysql
  jpa:
    show-sql: true

server:
  port: 8080

  application:
    name: university-student-portal
